name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: coderunner:latest

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"

    - name: Install dependencies
      run: |
        cd tests
        poetry install

    - name: Run the coderunner container
      run: |
        docker run -d -p 8000:8000 --name coderunner coderunner:latest
        sleep 4

    - name: Run tests
      run: |
        cd tests
        poetry run pytest test_execute.py -vv

    - name: Docker logs on failure
      if: failure()
      run: docker logs coderunner

    - name: Stop and remove container
      if: always()
      run: docker stop coderunner && docker rm coderunner
